#Using random library to generate pseudo-random numbers

import random

def guess():
  """
  A simple game where the user try the guess the random 
  number generated by the computer.
  """
  x = int(input('Set the limit: '))
  random_number = random.randint(1, x)
  guess = 0
  
  while guess != random_number:
    guess = int(input(f'Guess a number between 1 and {x}: '))
    if guess < random_number:
      print("Too low...")
    elif guess > random_number:
      print("Nop, too high.")

  print(f'Oh, bingo! {random_number} is right.')


def computerGuess():
  """
  A simple game where the computer try to guess de number
  chosen by the user.
  """
  x = int(input('Set the limit: '))
  low = 1
  high = x
  feedback = ''

  while feedback != 'c':
    if low != high:
        guess = random.randint(low, high)
    else: guess = low
    feedback = input(f'Is {guess} to high (H), too low(L) or correct(C)?').lower()
    if feedback == 'h':
      high = guess - 1
    elif feedback == 'l':
      low = guess + 1
    elif feedback != 'c':
      return print('Stop being silly!')       
  
  print(f'Oh, computer bingo! {guess} is right.')



